### ISSUE TITLE
is there a maven repo for CC

### ISSUE THREAD

**Issue by loordgek** [SquidDev-CC/ComputerCraft#3]
^

**Comment by SquidDev** [comment]
[c3i acts as a maven repo](https://cc.crzd.me/maven/). You can do something like:

```groovy
repositories {
  maven { url "https://cc.crzd.me/maven/" }
}

dependencies {
  deobfCompile "dan200.computercraft:ComputerCraft:1.80pr1-build5"
}
```

See [Plethora's build file](https://github.com/SquidDev-CC/plethora/blob/minecraft-1.12/build.gradle) for a more complete example.

**Comment by SquidDev** [comment]
Try just using `compile` then. I'm not sure why it's not deobfuscating it.

**Comment by loordgek** [comment]
that worked thank you
